version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    environment:
      - NODE_ENV: development
    working_directory: ~/react-state-patterns
    steps:
      - checkout
      - restore_cache:
          key: react-state-patterns-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn Install
          command: |
            yarn install
      - save_cache:
          key: react-state-patterns-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/react-state-patterns/node_modules
      - run:
          name: Run JS Tests
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
