version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: |
            yarn check || yarn install
      - run:
          name: Run JS Tests
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
